     CREATE TABLE IF NOT EXISTS campeonato (
id VARCHAR(100) PRIMARY KEY NOT NULL,
titulo VARCHAR(100) NOT NULL,
data_inicio DATE NOT NULL,
data_final DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS modalidade (
id VARCHAR(100) PRIMARY KEY NOT NULL,
nome_modalidade VARCHAR(100) NOT NULL UNIQUE,
descricao text,
limite_pessoas INT NOT NULL,
campeonato_id VARCHAR(100) NOT NULL,
valor_por_pessoas INT NOT NULL,
type BOOLEAN NOT NULL,
FOREIGN KEY(campeonato_id) REFERENCES campeonato(id)
);

CREATE TABLE IF NOT EXISTS times (
id VARCHAR(100) PRIMARY KEY NOT NULL,
nome VARCHAR(100) NOT NULL,
sala VARCHAR(100),
modalidade_id VARCHAR(100) NOT NULL,
status VARCHAR(100) NOT NULL,
pontos INT DEFAULT(0),
FOREIGN KEY(modalidade_id) REFERENCES modalidade(id)
);

CREATE TABLE IF NOT EXISTS jogador (
id VARCHAR(100) PRIMARY KEY NOT NULL,
nome VARCHAR(100) NOT NULL,
sala VARCHAR(100) NOT NULL,
time_id VARCHAR(100) NOT NULL,
FOREIGN KEY(time_id) REFERENCES times(id));

CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    tipo VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS refresh_token (
    id VARCHAR(36) PRIMARY KEY,
    expiresIn INT NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);